export interface AIModel {
  id: string;
  name: string;
  provider: string;
  category: "reasoning" | "general" | "coding" | "vision" | "small";
  isFree: boolean;
  description?: string;
}

export const AI_MODELS: AIModel[] = [
  // Reasoning Models
  {
    id: "deepseek/deepseek-r1:free",
    name: "DeepSeek R1",
    provider: "DeepSeek",
    category: "reasoning",
    isFree: true,
    description: "Advanced reasoning model",
  },
  {
    id: "deepseek/deepseek-r1-0528:free",
    name: "DeepSeek R1 0528",
    provider: "DeepSeek",
    category: "reasoning",
    isFree: true,
    description: "Latest reasoning model",
  },
  {
    id: "deepseek/deepseek-r1-distill-llama-70b:free",
    name: "DeepSeek R1 Distill Llama 70B",
    provider: "DeepSeek",
    category: "reasoning",
    isFree: true,
    description: "Distilled reasoning model",
  },
  {
    id: "tngtech/deepseek-r1t2-chimera:free",
    name: "DeepSeek R1T2 Chimera",
    provider: "TNG",
    category: "reasoning",
    isFree: true,
    description: "Hybrid reasoning model",
  },
  {
    id: "tngtech/deepseek-r1t-chimera:free",
    name: "DeepSeek R1T Chimera",
    provider: "TNG",
    category: "reasoning",
    isFree: true,
    description: "Chimera reasoning variant",
  },
  {
    id: "microsoft/mai-ds-r1:free",
    name: "MAI DS R1",
    provider: "Microsoft",
    category: "reasoning",
    isFree: true,
    description: "Microsoft reasoning model",
  },
  {
    id: "arliai/qwq-32b-arliai-rpr-v1:free",
    name: "QwQ 32B RpR v1",
    provider: "ArliAI",
    category: "reasoning",
    isFree: true,
    description: "Reasoning and problem-solving",
  },
  {
    id: "alibaba/tongyi-deepresearch-30b-a3b:free",
    name: "Tongyi DeepResearch 30B A3B",
    provider: "Tongyi",
    category: "reasoning",
    isFree: true,
    description: "Deep research model",
  },

  // General Purpose Models
  {
    id: "deepseek/deepseek-chat-v3-0324:free",
    name: "DeepSeek V3 0324",
    provider: "DeepSeek",
    category: "general",
    isFree: true,
    description: "Latest general model",
  },
  {
    id: "deepseek/deepseek-chat-v3.1:free",
    name: "DeepSeek V3.1",
    provider: "DeepSeek",
    category: "general",
    isFree: true,
    description: "Enhanced V3 model",
  },
  {
    id: "qwen/qwen3-235b-a22b:free",
    name: "Qwen3 235B A22B",
    provider: "Qwen",
    category: "general",
    isFree: true,
    description: "Large-scale model",
  },
  {
    id: "qwen/qwen3-30b-a3b:free",
    name: "Qwen3 30B A3B",
    provider: "Qwen",
    category: "general",
    isFree: true,
    description: "Mid-size general model",
  },
  {
    id: "qwen/qwen3-14b:free",
    name: "Qwen3 14B",
    provider: "Qwen",
    category: "general",
    isFree: true,
    description: "Efficient general model",
  },
  {
    id: "qwen/qwen3-4b:free",
    name: "Qwen3 4B",
    provider: "Qwen",
    category: "general",
    isFree: true,
    description: "Compact general model",
  },
  {
    id: "qwen/qwen2.5-72b-instruct:free",
    name: "Qwen2.5 72B Instruct",
    provider: "Qwen",
    category: "general",
    isFree: true,
    description: "Instruction-tuned model",
  },
  {
    id: "meta-llama/llama-3.3-70b-instruct:free",
    name: "Llama 3.3 70B Instruct",
    provider: "Meta",
    category: "general",
    isFree: true,
    description: "Meta's flagship model",
  },
  {
    id: "meta-llama/llama-3.3-8b-instruct:free",
    name: "Llama 3.3 8B Instruct",
    provider: "Meta",
    category: "general",
    isFree: true,
    description: "Efficient Llama model",
  },
  {
    id: "meta-llama/llama-3.2-3b-instruct:free",
    name: "Llama 3.2 3B Instruct",
    provider: "Meta",
    category: "general",
    isFree: true,
    description: "Compact Llama model",
  },
  {
    id: "meta-llama/llama-4-maverick:free",
    name: "Llama 4 Maverick",
    provider: "Meta",
    category: "general",
    isFree: true,
    description: "Next-gen Llama",
  },
  {
    id: "meta-llama/llama-4-scout:free",
    name: "Llama 4 Scout",
    provider: "Meta",
    category: "general",
    isFree: true,
    description: "Llama 4 variant",
  },
  {
    id: "nousresearch/hermes-3-llama-3.1-405b:free",
    name: "Hermes 3 405B Instruct",
    provider: "Nous",
    category: "general",
    isFree: true,
    description: "Large instruction model",
  },
  {
    id: "openai/gpt-oss-20b:free",
    name: "GPT OSS 20B",
    provider: "OpenAI",
    category: "general",
    isFree: true,
    description: "Open-source GPT variant",
  },
  {
    id: "moonshotai/kimi-k2:free",
    name: "Kimi K2 0711",
    provider: "MoonshotAI",
    category: "general",
    isFree: true,
    description: "Kimi assistant model",
  },
  {
    id: "meituan/longcat-flash-chat:free",
    name: "LongCat Flash Chat",
    provider: "Meituan",
    category: "general",
    isFree: true,
    description: "Fast chat model",
  },
  {
    id: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
    name: "Venice Uncensored",
    provider: "Venice",
    category: "general",
    isFree: true,
    description: "Uncensored model",
  },

  // Coding Models
  {
    id: "qwen/qwen3-coder:free",
    name: "Qwen3 Coder 480B A35B",
    provider: "Qwen",
    category: "coding",
    isFree: true,
    description: "Large coding model",
  },
  {
    id: "qwen/qwen2.5-coder-32b-instruct:free",
    name: "Qwen2.5 Coder 32B Instruct",
    provider: "Qwen",
    category: "coding",
    isFree: true,
    description: "Code generation specialist",
  },
  {
    id: "kwaipilot/kat-coder-pro:free",
    name: "Kat Coder",
    provider: "Kwaipilot",
    category: "coding",
    isFree: true,
    description: "Coding assistant",
  },
  {
    id: "agentica-org/deepcoder-14b-preview:free",
    name: "Deepcoder 14B Preview",
    provider: "Agentica",
    category: "coding",
    isFree: true,
    description: "Deep code understanding",
  },
  {
    id: "deepseek/deepseek-r1-0528-qwen3-8b:free",
    name: "DeepSeek R1 0528 Qwen3 8B",
    provider: "DeepSeek",
    category: "coding",
    isFree: true,
    description: "Hybrid coding model",
  },

  // Vision Models
  {
    id: "qwen/qwen2.5-vl-32b-instruct:free",
    name: "Qwen2.5 VL 32B Instruct",
    provider: "Qwen",
    category: "vision",
    isFree: true,
    description: "Vision-language model",
  },
  {
    id: "nvidia/nemotron-nano-12b-v2-vl:free",
    name: "Nemotron Nano 12B 2 VL",
    provider: "NVIDIA",
    category: "vision",
    isFree: true,
    description: "Vision model",
  },

  // Small/Fast Models
  {
    id: "google/gemini-2.0-flash-exp:free",
    name: "Gemini 2.0 Flash Experimental",
    provider: "Google",
    category: "small",
    isFree: true,
    description: "Fast experimental model",
  },
  {
    id: "google/gemma-3-27b-it:free",
    name: "Gemma 3 27B",
    provider: "Google",
    category: "small",
    isFree: true,
    description: "Gemma large variant",
  },
  {
    id: "google/gemma-3-12b-it:free",
    name: "Gemma 3 12B",
    provider: "Google",
    category: "small",
    isFree: true,
    description: "Gemma mid-size",
  },
  {
    id: "meta-llama/llama-3.2-3b-instruct:free",
    name: "Gemma 3 4B",
    provider: "Google",
    category: "small",
    isFree: true,
    description: "Compact Gemma",
  },
  {
    id: "google/gemma-3n-e4b-it:free",
    name: "Gemma 3n 4B",
    provider: "Google",
    category: "small",
    isFree: true,
    description: "Nano Gemma 4B",
  },
  {
    id: "google/gemma-3n-e2b-it:free",
    name: "Gemma 3n 2B",
    provider: "Google",
    category: "small",
    isFree: true,
    description: "Nano Gemma 2B",
  },
  {
    id: "mistralai/mistral-small-24b-instruct-2501:free",
    name: "Mistral Small 3",
    provider: "Mistral",
    category: "small",
    isFree: true,
    description: "Latest small Mistral",
  },
  {
    id: "mistralai/mistral-small-3.2-24b-instruct:free",
    name: "Mistral Small 3.2 24B",
    provider: "Mistral",
    category: "small",
    isFree: true,
    description: "Mistral 3.2 variant",
  },
  {
    id: "mistralai/mistral-small-3.1-24b-instruct:free",
    name: "Mistral Small 3.1 24B",
    provider: "Mistral",
    category: "small",
    isFree: true,
    description: "Mistral 3.1 variant",
  },
  {
    id: "mistralai/mistral-nemo:free",
    name: "Mistral Nemo",
    provider: "Mistral",
    category: "small",
    isFree: true,
    description: "Compact Mistral",
  },
  {
    id: "mistralai/mistral-7b-instruct:free",
    name: "Mistral 7B Instruct",
    provider: "Mistral",
    category: "small",
    isFree: true,
    description: "Classic Mistral",
  },
  {
    id: "nvidia/nemotron-nano-9b-v2:free",
    name: "Nemotron Nano 9B V2",
    provider: "NVIDIA",
    category: "small",
    isFree: true,
    description: "Nano model v2",
  },
  {
    id: "minimax/minimax-m2:free",
    name: "MiniMax M2",
    provider: "MiniMax",
    category: "small",
    isFree: true,
    description: "MiniMax model",
  },
  {
    id: "z-ai/glm-4.5-air:free",
    name: "GLM 4.5 Air",
    provider: "Z.AI",
    category: "small",
    isFree: true,
    description: "Lightweight GLM",
  },
];

export const MODEL_CATEGORIES = [
  { id: "all", label: "All Models", icon: "🤖" },
  { id: "reasoning", label: "Reasoning", icon: "🧠" },
  { id: "general", label: "General", icon: "💬" },
  { id: "coding", label: "Coding", icon: "💻" },
  { id: "vision", label: "Vision", icon: "👁️" },
  { id: "small", label: "Fast", icon: "⚡" },
] as const;

export const MODEL_PROVIDERS = [
  "All",
  "DeepSeek",
  "Qwen",
  "Meta",
  "Google",
  "Mistral",
  "NVIDIA",
  "OpenAI",
  "Microsoft",
  "TNG",
  "Nous",
  "MoonshotAI",
  "Meituan",
  "Venice",
  "Kwaipilot",
  "Agentica",
  "ArliAI",
  "MiniMax",
  "Z.AI",
  "Tongyi",
] as const;
