// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xduxwfbbqqhzolykhljc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkdXh3ZmJicXFoem9seWtobGpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MDUxODQsImV4cCI6MjA2NzE4MTE4NH0.9sC0YJo9Fg33uL_zMdwiQihr5Ry-6QEoHcCTTHW2Lvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});